### PR TITLE
Add `random-case`

### PR DESCRIPTION
**Pull request by nrabins**
I fully acknowledge that this is dumb.

I wasn't able to get this to compile and run tests locally, but the logic is pretty straightforward. I'm worried about having missed something from copy-pasting swap-case.

This is my first time doing something like this, so the odds of it being correct while developing blind are very small.

Thanks for the consideration!

### CODE REVIEW

**Comment by justaskclaire** [comment]
I approve of this.

Just _morally_.

**Comment by blakeembrey** [comment]
Thanks! I'll need to find a different name due to the current on being taken (with the same functionality) already: https://www.npmjs.com/package/random-case.

**Comment by blakeembrey** [comment]
Alternative name ideas: `shuffle-case` or `sponge-case`? Any preference?

**Comment by nrabins** [comment]
No preference at all. `sponge-case` is kind of cute :)

**Pull request merged**
