### PR TITLE
Changes title case provider package

### PR DESCRIPTION
**Pull request by deiga**
This package has some logic to how stuff is title cased and it does not swallow characters.

### CODE REVIEW

**Comment by blakeembrey** [comment]
Thanks, but I'm not currently looking at changing this to another package. I think, if anything, I'd like to remove all `title-case` functionality or update the `title-case` package directly.

**Comment by deiga** [comment]
@blakeembrey Would you elaborate as to why? I get the removal idea, but why would you deny your users an actually functioning version and instead plan to maybe update the current one yourself?

**Comment by blakeembrey** [comment]
Because it's a subjective feature and will likely end up with additional issues. I have to deal with those issues and I'd like to have control over that. Also, any change now is a major version change so I'd like to do it right - either make it so I have control to improve later or remove the feature altogether. Overall, I'd prefer to leave it the same as the current implementation is obvious and non-subjective, but I get this issue enough that I'd like to remove it forever - whichever way is easiest. Writing that out, I'm thinking maybe I should remove it altogether or rename `title-case` to something more fitting. Do you have a better name for the current casing behaviour?

**Comment by deiga** [comment]
Okay, I get the need for control. 
The current behaviour is a bit weird (with all the destructiveness) that it's really hard to name it.

If you decide to want to build the system for yourself, here is a pretty good implementation (on which the titlecase package is based on) https://github.com/gouch/to-title-case/blob/master/to-title-case.js

**Comment by blakeembrey** [comment]
Absolutely. I think there's a lot of good packages for "real" title casing behaviour that should be used if that's what people want. I think I would like to see both exist, but start by renaming `titleCase` in this module better so it's not confused with proper title casing. Not sure what that would be though, so if we can't find a more appropriate name maybe it'll be better to remove it.

**Pull request closed without merging**
