### PR TITLE
add binary-case

### PR DESCRIPTION
**Pull request by Gi60s**
You've got an awesome library going on here. I thought binary-case might be good to add.

Binary-case is especially useful when you're creating an object that has to have multiple property keys with the same name but case doesn't matter.

### CODE REVIEW

**Comment by blakeembrey** [comment]
Hi! Thanks for the PR, but I don't think I want to include it at this time. It doesn't really fit with the rest of the project smoothly (although some of the modules already there don't either) and, at this point in time, I don't wish to add another dependency to maintain. I would be happy to add a section at the bottom of README linking to your project.

I've never seen this sort of approach personally either, do you have a solid example of using this?

**Comment by Gi60s** [comment]
Thanks for the reply. It can be frustrating when you never hear back and nothing ever happens. I'm not offended by your decision not to include it, but if you want to include a link somewhere I wouldn't complain either. I'll leave that up to you.

The use case for this is interesting. I ran into a situation where I had to create an object with multiple keys that had the same case-insensitive equivalent.

I'm using Amazon Web Services and within that I'm using the API gateway and a lambda. The gateway routes HTTP requests to the lambda (which is essentially just a function). The lambda receives the request as an object and returns the response as an object.

Something interesting about the response I send back to the gateway is that the headers must be set using a plain object. That means that I can only have unique headers in the response, which seems fine until you realize that when setting cookies you need multiple 'set-cookie' headers in order to send multiple cookies back to the client. (Reference: https://www.nczonline.net/blog/2009/05/05/http-cookies-explained/)

The header might look like this:

```
{
    'Content-Type': 'text/html',
    'Set-Cookie': 'cookie1=foo',
    'Set-Cookie': 'cookie2=bar'
}
```

Fortunately browsers don't mind the case of the header keys being set, so I can change the case of the headers and get the desired effect.

```
{
    'Content-Type': 'text/html',
    'Set-Cookie': 'cookie1=foo',
    'set-cookie': 'cookie2=bar'
}
```

Unfortunately the number of cookies being set is not determined by my lambda function, so I had to come up with a way to allow a variation of casing for each cookie that was to be set.

**Comment by blakeembrey** [comment]
I haven't used lambda before, can you link me to the response examples? Can't you pass an array of strings as the `Set-Cookie` header instead?

**Comment by Gi60s** [comment]
I wasn't saying that you were slow. You were quick. Sometimes people never respond though and nothing happens.

You can't set an array unfortunately. Here is a post that describes this problem: https://forums.aws.amazon.com/thread.jspa?messageID=701434

There is a work around, but the work around requires configuration outside of the lambda that generates the response: https://aws.amazon.com/blogs/compute/simply-serverless-using-aws-lambda-to-expose-custom-cookies-with-api-gateway/

At the bottom of this page you'll see the expected output format for the lambda: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html#api-gateway-simple-proxy-for-lambda-output-format#api-gateway-simple-proxy-for-lambda-output-format

**Comment by blakeembrey** [comment]
No worries, I misinterpreted 😄  That's amazing, glad you found a workaround then.

**Comment by Gi60s** [comment]
👍

**Pull request closed without merging**
